### ISSUE TITLE
Installation issues python 3.10.12

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/inext_cli#2]
Cannot run `-h` option without getting syntax error

```
Traceback (most recent call last):
  File "/home/user/scripts/inext/.venv/bin/inext_cli", line 33, in <module>
    sys.exit(load_entry_point('inext-cli==0.0.1', 'console_scripts', 'inext_cli')())
  File "/home/user/scripts/inext/.venv/bin/inext_cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/scripts/inext/.venv/lib/python3.10/site-packages/inext_cli/main.py", line 8, in <module>
    from . import push, pull, download
  File "/home/user/scripts/inext/.venv/lib/python3.10/site-packages/inext_cli/push.py", line 1, in <module>
    from inext_cli.classes.push import push
  File "/home/user/scripts/inext/.venv/lib/python3.10/site-packages/inext_cli/classes/push.py", line 3, in <module>
    from inext_cli.classes.sendFile import sendFile
  File "/home/user/scripts/inext/.venv/lib/python3.10/site-packages/inext_cli/classes/sendFile.py", line 1, in <module>
    from inext_cli.classes.query import query_constructor
  File "/home/user/scripts/inext/.venv/lib/python3.10/site-packages/inext_cli/classes/query.py", line 74
    return f'query {{\n {"\n".join(results)}       }}'
                                                        ^
SyntaxError: f-string expression part cannot include a backslash
```

**Comment by Takadonet** [comment]
Solved by install newer version of python > 3.12.4
